class_name FighterEnums

enum State {
	IDLE, WALK_FORWARD, WALK_BACK, DASH_FORWARD, BACKSTEP, RUN, DUCK,
	JUMP, JUMP_FORWARD, JUMP_BACKWARD, 
	ATTACK_1, ATTACK_2, ATTACK_3, ATTACK_4,
	ATTACK_FORWARD_1, ATTACK_BACK_1, ATTACK_LOW_1, ATTACK_UP_1,
	ATTACK_FORWARD_2, ATTACK_BACK_2, ATTACK_LOW_2, ATTACK_UP_2,
	ATTACK_FORWARD_3, ATTACK_BACK_3, ATTACK_LOW_3, ATTACK_UP_3,
	ATTACK_FORWARD_4, ATTACK_BACK_4, ATTACK_LOW_4, ATTACK_UP_4,
	ATTACK_RUN_1, ATTACK_RUN_2, ATTACK_RUN_3, ATTACK_RUN_4,
	HIT_STUN, KNOCKDOWN, GROUNDED,
}
